### ISSUE TITLE
Developer in Play Store appears to be an unknown company?

### ISSUE THREAD

**Issue by hpka** [destil/GPS-Averaging#8]
It seems the developer in the play store has changed to "DoubleApp Xco" and their only other apps are a flashlight app and something about unused Nigerian network & bank codes. This is a rather concerning change.

**Comment by davidvavra** [comment]
Yes I didn't have time to maintain the app and it was scheduled to be removed from Play Store few days ago because of some security issue. So instead of having it removed, I sold the app to this company. There will be more ads there, but otherwise it's harmless. Btw the original code is all here, feel free to fork it and build the original version.
